### ISSUE TITLE
Ajout des départements

### ISSUE THREAD

**Issue by tmerlier** [sgmap/api-communes#32]
## Départements
- [x] Ajout du département de rattachement pour chaque commune #27 
- [x] Possibilité de restreindre la recherche de commune à un département #28 
- [x] Route `/departements?` => Rechercher des départements #29 
- [x] Route `/departements/{code}` => Obtenir les informations d'un département #30 
- [x] Route `/departements/{code}/communes` => Lister les communes d'une région #31
