### ISSUE TITLE
Ajout des régions

### ISSUE THREAD

**Issue by tmerlier** [sgmap/api-communes#41]
## Régions
- [x] Ajout de la région de rattachement pour chaque commune #35 
- [x] Possibilité de restreindre la recherche de commune à une région #36 
- [x] Route `/regions?` => Rechercher des régions  #38 
- [x] Route `/regions/{code}` => Obtenir les informations d'une région #39 
- [x] Route `/regions/{code}/departements` => Lister les départements d'une région #40
